"""add is_published to posts

Revision ID: ec131c6ea8c2
Revises: f8e5c937dc5d
Create Date: 2025-11-17 14:52:39.519676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec131c6ea8c2'
down_revision: Union[str, None] = 'f8e5c937dc5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_published', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_published')
    # ### end Alembic commands ###
